pull_request_rules:
  - name: Automatic merge on CI
    conditions:
      - or:
        - base=main
        - base=dev
    actions:
      merge:
        method: merge
queue_rules:
  - name: default
    queue_conditions:
      - check-success = test
