# name: ☁️Deploy

# on:
#   workflow_run:
#     workflows: ["🐍Build"]
#     branches: [ "main" ]
#     types: 
#       - completed

# jobs:
#   deploy-deta:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3.5.2
      # - name: Deploy to Deta
      #   uses: BogDAAAMN/deta-deploy-action@v1.0.1
      #   with:
      #     deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
      #     deta-name: ${{ secrets.DETA_STAGING_MICRO_NAME }}
      #     deta-project: ${{ secrets.DETA_PROJECT_NAME }}
name: ☁️Deploy

on:
  workflow_run:
    workflows: [🐍Build]
    branches: [main]
    types:
     - completed

jobs:
  push_to_registry:
    name: 🐳 Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Log in to the ghcr registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mraniki/dxsp
          tags: latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./examples/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: 'Build Inventory Image'
      #   run: |
      #     docker build -f examples/Dockerfile --tag ghcr.io/mraniki/dxsp:latest
      #     docker push ghcr.io/mraniki/dxsp:latest 
