
name: 🐍Build

on:
  push:
    branches: [ "main"]
  pull_request:
   branches: [ "main"]
   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip twine
        pip install poetry
        poetry install
    - name: Build package
      run: poetry build

  release:
      # Run semantic release:
      # - Update CHANGELOG.md
      # - Update version in code
      # - Create git tag
      # - Create GitHub release
      # - Publish to PyPI
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.33.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_API_TOKEN }}
          additional_options: --patch

#
    # BREAKING CHANGE:
    # feat: A new feature
    # fix: A bug fix
    # docs: Documentation only changes
    # style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    # refactor: A code change that neither fixes a bug nor adds a feature
    # perf: A code change that improves performance
    # test: Adding missing or correcting existing tests
    # chore: Changes to the build process or auxiliary tools and libraries such as documentation generation

         

